lib/AccessSystem/Schema/Result/Person.pm
Recent changes removed the ability to cope with yearly payments for 10% off the usual fee - this adds them back in.
Every day a script runs to check each member, and whether a) their membership is on the verge of expiring, and b) if they have paid in a sufficient amount to cover another months membership.
This expands the code to check if the member's balance (paid in amount) is >= one year's membership, and if so add them an entire year of membership instead of just a month.
=> Cope with yearly fee payments, 1 year for 90% of usual fees

AccessSystem-Schema-7.0-8.0-MySQL.sql, AccessSystem-Schema-7.0-8.0-PostgreSQL.sql, AccessSystem-Schema-7.0-8.0-SQLite.sql, AccessSystem-Schema-8.0-MySQL.sql, AccessSystem-Schema-8.0-PostgreSQL.sql, AccessSystem-Schema-8.0-SQLite.sql, cpanfile.snapshot, lib/AccessSystem/Form/Person.pm, lib/AccessSystem/Schema.pm, lib/AccessSystem/Schema/Result/Person.pm, root/src/main.js
Also made the field descriptions less in-jokey
=> More "register" questions including vouchers + how member got here

.gitignore, AccessSystem-Schema-8.0-9.0-MySQL.sql, AccessSystem-Schema-8.0-9.0-PostgreSQL.sql, AccessSystem-Schema-8.0-9.0-SQLite.sql, AccessSystem-Schema-9.0-MySQL.sql, AccessSystem-Schema-9.0-PostgreSQL.sql, AccessSystem-Schema-9.0-SQLite.sql, cpanfile, cpanfile.snapshot, lib/AccessSystem/API/Controller/Root.pm, lib/AccessSystem/Schema.pm, lib/AccessSystem/Schema/Result/Person.pm, lib/AccessSystem/Schema/Result/ToolStatus.pm, lib/AccessSystem/Schema/ResultSet/Person.pm, script/access_telegram.pl
Adds a telegram bot (and related table changes) so that members can associate their telegram account with their makerspace membership, then use the bot to ask about the state of their membership, make purchases, etc
=> Access bot

cpanfile, cpanfile.snapshot, lib/AccessSystem/TelegramBot.pm
Pay has a "keyboard" that collects items to pay for - currently only
pre-known ones.
=> Add /prices, /balance and /pay

lib/AccessSystem/TelegramBot.pm
/make_inductor &lt;name&gt; on &lt;tool&gt;
Also made "/inductions" default to current user if not supplied
=> Add "make_inductor" (for directors, aka inductors on "the door")

lib/AccessSystem/Schema.pm, sql/AccessSystem-Schema-12.0-13.0-MySQL.sql, sql/AccessSystem-Schema-12.0-13.0-PostgreSQL.sql, sql/AccessSystem-Schema-12.0-13.0-SQLite.sql, sql/AccessSystem-Schema-13.0-MySQL.sql, sql/AccessSystem-Schema-13.0-PostgreSQL.sql, sql/AccessSystem-Schema-13.0-SQLite.sql, sql/Update-11.0-12.0-PostgreSQL.sql, sql/Update-11.0-12.0-SQLite.sql
=> Fix tiers changed field name in db

lib/AccessSystem/Schema/Result/Person.pm, root/src/main.js
Also ensure we can update as well as insert "null" colours (for folks switching back from sponsor to standard tiers)
(Tests.. we should write tests, less breakage that way)
=> Ensure we default to displaying colour picking when already sponsor

lib/AccessSystem/Form/Person.pm, lib/HTML/FormHandler/Widget/Wrapper/ASBootstrap4.pm
Now with readable checkboxes! Thanks to @notquitehere !
=> Improve register form layout on mobile devices

lib/AccessSystem/Schema/Result/Tier.pm, lib/AccessSystem/Schema/ResultSet/Person.pm, lib/AccessSystem/TelegramBot.pm
/whois <partial name> returns whether that member exists, which tier they are in, and their current valid / paid status
=> Add the /whois command to the telegram bot

lib/Catalyst/View/Email.pm
.. Forgot this in the previous PR, oops!
=> Overload Catalyst::View::Email to send an existing Email::MIME

lib/AccessSystem/API/Controller/Root.pm, lib/AccessSystem/Emailer.pm, lib/AccessSystem/Schema/Result/Person.pm, script/send_communications.pl
send_communications script still needed config to generate the email, so moved it to Emailer where we already had config data
=> Move generate_email to Emailer (deal with consequences)

lib/AccessSystem/Emailer.pm, t/emailer.t
Something something basic testing
=> Make emailer work :P

lib/AccessSystem/API/Controller/Root.pm, lib/AccessSystem/Form/Person.pm, lib/AccessSystem/Schema.pm, lib/AccessSystem/Schema/Result/Communication.pm, lib/AccessSystem/Schema/Result/Person.pm, lib/AccessSystem/Schema/Result/Vehicle.pm, lib/AccessSystem/TelegramBot.pm, root/src/profile.tt, sql/AccessSystem-Schema-14.0-15.0-MySQL.sql, sql/AccessSystem-Schema-14.0-15.0-PostgreSQL.sql, sql/AccessSystem-Schema-14.0-15.0-SQLite.sql, sql/AccessSystem-Schema-15.0-MySQL.sql, sql/AccessSystem-Schema-15.0-PostgreSQL.sql, sql/AccessSystem-Schema-15.0-SQLite.sql
Optional vehicle number plate storage for members, to assist us passing this to BSS house for ANPR system:
* Persons (members) can have 0-many vehicles, identified by a number plate string, and a date added
* Register person form includes an (optional) field to add an initial vehicle
* Telegram bot allows members (must be identified) to add vehicles
* Vehicle plates can be max 7-chars long, any spaces and non-letter/digit characters will be removed
* Profile view lists existing vehicles
* List-all-vehicles (plates) list outputs plates of all current members
=> Added vehicles to database and supporting methods

lib/AccessSystem/TelegramBot.pm
...and director tag for ->authorize.
=> Telegram /door_log command

lib/AccessSystem/Schema/ResultSet/Person.pm
=> Only non "pending" members may access the tools (also the Door)

NOTES.txt, lib/AccessSystem/API/Controller/Root.pm, lib/AccessSystem/Emailer.pm, lib/AccessSystem/Schema.pm, lib/AccessSystem/Schema/Result/UsageLog.pm, script/from_bank.pl, sql/AccessSystem-Schema-15.0-16.0-MySQL.sql, sql/AccessSystem-Schema-15.0-16.0-PostgreSQL.sql, sql/AccessSystem-Schema-15.0-16.0-SQLite.sql, sql/AccessSystem-Schema-16.0-MySQL.sql, sql/AccessSystem-Schema-16.0-PostgreSQL.sql, sql/AccessSystem-Schema-16.0-SQLite.sql
Tracks tool usage in UsageLog table, should collect per usage stats: who, when started, which tool, how long used for
=> Add tool_access endpoint, for thing controller

script/fix_door_pending.pl
=> One-time fix for current valid members:

lib/AccessSystem/TelegramBot.pm
(allowed->find is_admin was only using the tool_id key)
=> Inductions should require an actual inductor

lib/AccessSystem/Schema/Result/Person.pm
(Assuming pg boolean result is 't', not 'true')
=> Just set door to not-pending, every payment

root/src/emails/first_payment/first_payment.html, root/src/emails/first_payment/first_payment.txt, root/src/emails/rejoin_payment/rejoin_payment.html, root/src/emails/rejoin_payment/rejoin_payment.txt, root/src/emails/send_membership_email/send_membership_email.html, root/src/emails/send_membership_email/send_membership_email.txt
fixed url not working quite as intended
=> fixed emails again

lib/AccessSystem/API/Controller/Root.pm, lib/AccessSystem/Schema/Result/Person.pm
This allows us to remind them again if they again take a payment break.
Updated the manual reminders (via nudge_member) so they can be sent more than once (but not more than once per day) - this is the non-automatic reminder method
NB: Only tested as far as compiling it.... need a whole test suite!
=> If/when member rejoins, delete any reminder email they were sent

lib/AccessSystem/Schema/Result/Communication.pm, lib/AccessSystem/Schema/Result/Person.pm
Instead rely on deletion when rejoining
=> Do not force recreation of reminder emails

lib/AccessSystem/TelegramBot.pm
When using /tools to list a single tool, display the inductors list along with the status
=> Display tool's inductors (when querying one tool)

lib/AccessSystem/Schema.pm, lib/AccessSystem/Schema/Result/Allowed.pm, lib/AccessSystem/Schema/Result/Communication.pm, lib/AccessSystem/Schema/Result/Person.pm, lib/AccessSystem/Schema/Result/Tool.pm, lib/AccessSystem/TelegramBot.pm, script/inductions_history_from_telegram.pl, sql/AccessSystem-Schema-16.0-17.0-MySQL.sql, sql/AccessSystem-Schema-16.0-17.0-PostgreSQL.sql, sql/AccessSystem-Schema-16.0-17.0-SQLite.sql, sql/AccessSystem-Schema-17.0-MySQL.sql, sql/AccessSystem-Schema-17.0-PostgreSQL.sql, sql/AccessSystem-Schema-17.0-SQLite.sql
Amend telegram bot + thing-controller inductions to use it
By James, script to update existing inductions to add inducted_by using telegram group history
=> Add "inducted_by" field to allowed table

script/inductions_history_from_telegram.pl
Corrected some minor issues while running the inductions import (to add inducted_by to the db)
=> Telegram induction history import - minor tweaks after deploy ..

lib/AccessSystem/API/Controller/Root.pm
Tag-assigner inductees can assign tags to (new) members
=> Endpoint for tag assignment

lib/AccessSystem/API/Controller/Root.pm, lib/AccessSystem/Schema/ResultSet/Person.pm, t/ResultSetPerson.t
Complain about member not valid before complaining that they havent been 'inducted on the door'
=> Re-order error messages output on verify
